/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClientTile: typeof import('./src/components/ClientTile.vue')['default']
    ConfirmDeleteDialog: typeof import('./src/components/ConfirmDeleteDialog.vue')['default']
    ConnectionEditorDialog: typeof import('./src/components/editor/ConnectionEditorDialog.vue')['default']
    ConnectionsList: typeof import('./src/components/editor/ConnectionsList.vue')['default']
    DiagramNodePanel: typeof import('./src/components/editor/DiagramNodePanel.vue')['default']
    DiagramTab: typeof import('./src/components/editor/DiagramTab.vue')['default']
    ExportMenu: typeof import('./src/components/editor/ExportMenu.vue')['default']
    GridCell: typeof import('./src/components/editor/GridCell.vue')['default']
    HierarchyTree: typeof import('./src/components/HierarchyTree.vue')['default']
    MapBadge: typeof import('./src/components/MapBadge.vue')['default']
    MapSettingsInspector: typeof import('./src/components/editor/MapSettingsInspector.vue')['default']
    MapTabs: typeof import('./src/components/editor/MapTabs.vue')['default']
    MapWorkspace: typeof import('./src/components/editor/MapWorkspace.vue')['default']
    NewClientDialog: typeof import('./src/components/NewClientDialog.vue')['default']
    NewMapDialog: typeof import('./src/components/NewMapDialog.vue')['default']
    PainPointDialog: typeof import('./src/components/editor/PainPointDialog.vue')['default']
    PainPointEditor: typeof import('./src/components/editor/PainPointEditor.vue')['default']
    PasteDialog: typeof import('./src/components/editor/PasteDialog.vue')['default']
    ProcessDialog: typeof import('./src/components/ProcessDialog.vue')['default']
    RenameDialog: typeof import('./src/components/RenameDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepInspector: typeof import('./src/components/editor/StepInspector.vue')['default']
    StepRow: typeof import('./src/components/editor/StepRow.vue')['default']
    SubProcessDialog: typeof import('./src/components/SubProcessDialog.vue')['default']
    TableTab: typeof import('./src/components/editor/TableTab.vue')['default']
    TreeRail: typeof import('./src/components/workspace/TreeRail.vue')['default']
    WizardTab: typeof import('./src/components/editor/WizardTab.vue')['default']
    WorkspaceTopBar: typeof import('./src/components/workspace/WorkspaceTopBar.vue')['default']
  }
}
