<script setup>
// The diagram canvas's footer strip (BACKLOG 4.2): the node-type shape+color
// legend (same shapes DiagramTab.vue's own nodes render, via nodeShapes.js /
// nodeColors.js — one vocabulary, not a redrawn approximation) plus a
// generated-by/date line. Plain SVG nested inside DiagramTab.vue's <svg>, so
// it exports through the same render-to-SVG path as everything else on the
// canvas (PLAN G8) rather than needing separate export-only markup.
import { computed } from 'vue'
import { NODE_TYPE_NAMES, nodeTypeColor } from '@/diagram/nodeColors.js'
import { shapeGeometry, pointsAttr } from '@/diagram/nodeShapes.js'
import { legendPositions, LEGEND_ROW_HEIGHT, FOOTER_META_HEIGHT } from '@/diagram/diagramChrome.js'

const props = defineProps({
  width: { type: Number, required: true },
  y: { type: Number, required: true }, // top edge of the whole footer strip
  shapes: { type: Object, default: () => ({}) }, // node_type -> shape name (diagramMeta)
  generatedBy: { type: String, default: '' },
  generatedDate: { type: String, default: '' },
})

const ICON_W = 22
const ICON_H = 16

const legendItems = computed(() =>
  NODE_TYPE_NAMES.map((type, i) => ({
    type,
    hex: nodeTypeColor(type).hex,
    x: legendPositions(props.width, NODE_TYPE_NAMES.length)[i],
    geo: shapeGeometry({ x: ICON_W / 2, y: ICON_H / 2, w: ICON_W, h: ICON_H, shape: props.shapes[type] }),
  }))
)

const metaY = computed(() => props.y + LEGEND_ROW_HEIGHT + FOOTER_META_HEIGHT / 2 + 4)
</script>

<template>
  <g>
    <line x1="0" :y1="y" :x2="width" :y2="y" stroke="#e2e8f0" stroke-width="1" />

    <!-- legend: shape + color key, one entry per Node Type -->
    <g v-for="item in legendItems" :key="item.type" :transform="`translate(${item.x}, ${y + 9})`">
      <ellipse
        v-if="item.geo.kind === 'ellipse'"
        :cx="item.geo.cx"
        :cy="item.geo.cy"
        :rx="item.geo.rx"
        :ry="item.geo.ry"
        :fill="item.hex"
        fill-opacity="0.32"
        :stroke="item.hex"
        stroke-width="1.5"
      />
      <polygon
        v-else-if="item.geo.kind === 'polygon'"
        :points="pointsAttr(item.geo.points)"
        :fill="item.hex"
        fill-opacity="0.32"
        :stroke="item.hex"
        stroke-width="1.5"
      />
      <rect
        v-else
        :x="item.geo.x"
        :y="item.geo.y"
        :width="item.geo.width"
        :height="item.geo.height"
        :rx="item.geo.rx"
        :fill="item.hex"
        fill-opacity="0.32"
        :stroke="item.hex"
        stroke-width="1.5"
      />
      <text :x="ICON_W + 8" :y="ICON_H / 2" fill="#334155" font-size="10.5" dominant-baseline="middle">
        {{ item.type }}
      </text>
    </g>

    <!-- generated-by / date -->
    <text
      :x="width / 2"
      :y="metaY"
      fill="#94a3b8"
      font-size="10.5"
      text-anchor="middle"
    >
      Generated by {{ generatedBy }} · {{ generatedDate }}
    </text>
  </g>
</template>
